"""empty message

Revision ID: 1a7bf4057c11
Revises: 70e600696b7e
Create Date: 2020-10-29 16:37:52.767648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7bf4057c11'
down_revision = '70e600696b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('done', table_name='todos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('done', 'todos', ['done'], unique=True)
    # ### end Alembic commands ###
